# Copyright Contributors to the Open Cluster Management project
name: FOSSA License Scan

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'open-cluster-management-io'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Run FOSSA Scan
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
